include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-and-test"
      tarball-artifact-path: "${TARBALL_ARTIFACT_DIR}/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

variables:
  MESON_BUILD_DIR: _build
  TARBALL_ARTIFACT_DIR: "${MESON_BUILD_DIR}/meson-dist"

build-and-test:
  image: nixpkgs/nix:latest
  script:
    - eval "$(npins/export-shell-env.sh)"
    - meson setup "${MESON_BUILD_DIR}"
    - ninja -C "${MESON_BUILD_DIR}" clang-format-check
    - meson test -C "${MESON_BUILD_DIR}"
    - meson dist -C "${MESON_BUILD_DIR}" --include-subprojects
  artifacts:
    name: "Tarball"
    paths:
      - "${TARBALL_ARTIFACT_DIR}/"
